=== DanKalinin/BTConfiguration/Framework/Framework/Schemas/centralConfiguration.json
{
    "$schema" : "http://json-schema.org/draft-04/schema#",
    
    "definitions" : {
        
        "uuid" : {
            "type" : "string",
            "pattern" : "^[0-9A-F]{8}-([0-9A-F]{4}-){3}[0-9A-F]{12}$"
        },
        
        "unsignedNumber" : {
            "type" : "number",
            "minimum" : 0.0
        },
        
        "unsignedInteger" : {
            "type" : "integer",
            "minimum" : 0
        },
        
        "initialization" : {
            "type" : "object",
            
            "properties" : {
                "showPowerAlert" : {"type" : "boolean"},
                "restoreIdentifier" : {"type" : "string"}
            }
        },
        
        "scanning" : {
            "type" : "object",
            
            "properties" : {
                "allowDuplicates" : {"type" : "boolean"},
                "solicitedServices" : {
                    "type" : "array",
                    "items" : {"$ref" : "#/definitions/uuid"}
                }
            }
        },
        
        "connection" : {
            "type" : "object",
            
            "properties" : {
                "notifyOnConnection" : {"type" : "boolean"},
                "notifyOnDisconnection" : {"type" : "boolean"},
                "notifyOnNotification" : {"type" : "boolean"},
                "timeout" : {"$ref" : "#/definitions/unsignedNumber"},
                "attempts" : {"$ref" : "#/definitions/unsignedInteger"}
            }
        },
        
        "characteristic" : {
            "type" : "object",
            
            "properties" : {
                "name" : {"type" : "string"},
                "notify" : {"type" : "boolean"},
                "writeWithResponse" : {"type" : "boolean"}
            },
            
            "required" : ["name"]
        },
        
        "characteristics" : {
            "type" : "object",
            
            "patternProperties" : {
                "^[0-9A-F]{8}-([0-9A-F]{4}-){3}[0-9A-F]{12}$" : {"$ref" : "#/definitions/characteristic"}
            },
            
            "additionalProperties" : false,
            "minProperties" : 1
        },
        
        "service" : {
            "type" : "object",
            
            "properties" : {
                "name" : {"type" : "string"},
                "characteristics" : {"$ref" : "#/definitions/characteristics"}
            },
            
            "required" : ["name", "characteristics"]
        },
        
        "services" : {
            "type" : "object",
            
            "patternProperties" : {
                "^[0-9A-F]{8}-([0-9A-F]{4}-){3}[0-9A-F]{12}$" : {"$ref" : "#/definitions/service"}
            },
            
            "additionalProperties" : false,
            "minProperties" : 1
        }
    },
    
    "properties" : {
        "initialization" : {"$ref" : "#/definitions/initialization"},
        "scanning" : {"$ref" : "#/definitions/scanning"},
        "connection" : {"$ref" : "#/definitions/connection"},
        "services" : {"$ref" : "#/definitions/services"}
    },
    
    "required" : ["services"]
}

=== DanKalinin/BTConfiguration/App/App/CentralConfiguration.json
{
    "initialization" : {
        "showPowerAlert" : true,
        "restoreIdentifier" : "xxx"
    },
    
    "scanning" : {
        "allowDuplicates" : false,
        "solicitedServices" : []
    },
    
    "connection" : {
        "notifyOnConnection" : true,
        "notifyOnDisconnection" : true,
        "notifyOnNotification" : true,
        "timeout" : 2.0,
        "attempts" : 3
    },
    
    "services" : {
        "6E400001-B5A3-F393-E0A9-E50E24DCCA9E" : {
            "name" : "UART",
            "characteristics" : {
                "6E400002-B5A3-F393-E0A9-E50E24DCCA9E" : {
                    "name" : "TX",
                    "notify" : false
                },
                "6E400003-B5A3-F393-E0A9-E50E24DCCA9E" : {
                    "name" : "RX",
                    "notify" : true
                }
            }
        }
    }
}
